### ISSUE TITLE
Custon data object

### ISSUE THREAD

**Issue by marianobarraco** [alexgorbatchev/jquery-textext#142]
Hi.

I want to tag users signed to my app. I have a table, so I can load an object like this: {id: 662, name: 'Foo Bar'}.

What I need is to write the name (Foo Bar) as a tag and print the id (662) as the value on the input hidden in the form.

What I think will suit for us is this:
http://textextjs.com/manual/examples/tags-with-custom-data-objects.html

Any idea?

**Comment by marianobarraco** [comment]
Solved.

**Comment by martingg88** [comment]
can i know how you solve this? any example ? thanks
