### ISSUE TITLE
Create new Tag on enter event

### ISSUE THREAD

**Issue by jas-odoo** [alexgorbatchev/jquery-textext#161]
Hello,

 If I want to create new tag 'Act' and there is 'Action' tag in list then on on pressing Enter after typing 'Act' will select 'Action' from the list.
Let consider list of tags ['Action','Ecommerce']
Now I want create new Tag 'Act', after typing Act,it will autoselect first item from list(i.e 'Action' in our case) and when I press enter it will add 'Action' tag not create Act tag.

**Comment by CAyma63** [comment]
Try entering Act, a space, and then [Enter].

**Comment by jas-odoo** [comment]
Hello sir,
Thanks for reply.
This might work,but from usability point of view it is not so user friendly.

**Comment by sneha27** [comment]
Hello,

Seems you have added this query a long back. Did you get a better way to overcome this?
Will be helpful to me for my case too. 

Thanks
