### ISSUE TITLE
Validate on blur

### ISSUE THREAD

**Issue by wsalame** [alexgorbatchev/jquery-textext#199]
Instead of having to press Enter, is there a way to add the tag on the blur of the widget ? I managed to bind the blur event, but I can't figure out which function to call after that.

**Comment by viilveer** [comment]
Hi. Despite late answer, here is the solution I found. Might not be the cleanest - 
`var config = {
            plugins:'tags focus',
            tagsItems: $this.data('prefilldata'),
            ext: {
                focus: {
                    onBlur : function (e) {
                        if ($(e.currentTarget).val() != "") {
                            this._core._plugins.tags.onEnterKeyPress();
                            $(e.currentTarget).val("");
                        }
                    }
                }
           }
     }`

**Comment by wsalame** [comment]
Thanks ! Another workaround I ended up doing

```
$('#' + id).blur(defaultValue, function(e) {
      pressEnterKeyProgrammatically('#' + id, e.data);
});

function pressEnterKeyProgrammatically(selector, defaultValue) {
      if (defaultValue != $(selector).val() && $(selector).val() != '') {
        $(selector).trigger('enterKeyPress').val('');

        $(selector).off('blur'); //To avoid infine blur loop in Chrome
        $(selector).blur();

        $(selector).blur(defaultValue, function(e) {
          pressEnterKeyProgrammatically(selector, e.data);
        });
      }
    }
```
