### ISSUE TITLE
Allow user to click on a tag in the list of suggested tags to add it

### ISSUE THREAD

**Issue by jasondavis** [alexgorbatchev/jquery-textext#2]
It would be nice to be able to Click on a tag once it is in the suggestion list

**Comment by nevf** [comment]
I am very surprised that clicking on an item in the suggestion list doesn't select it. This seems like the most basic of desired behaviour.

**Comment by alexgorbatchev** [comment]
I agree, seems that I have overlooked this one.

**Comment by nevf** [comment]
Any idea when you'll implement mouse click selection?

**Comment by jasondavis** [comment]
jquery-textext is really an amazing project you got here, I mean I would rate it with the tagging ability of Stackoverflow and Facebook on the feature side of it, the only thing missing for me is the click ability, thanks for sharing your work with the world

**Comment by alexgorbatchev** [comment]
@jasondavis thnx!

Not sure when exactly I'd be able to get to it. It would be awesome if you guys could take a look at it :)

**Comment by jasondavis** [comment]
I would love to contribute but I am more of a backend coder, I am not currently skilled enough with Javascript.   I did take a look at the code though just to get an idea, and in Autocomplete plugin I found this  

```
p.onClick = function(e)
{
    var self   = this,
        target = $(e.target)
        ;

    if(target.is(CSS_DOT_SUGGESTION))
        self.selectFromDropdown();
};
```

I would imagine that is for doing what this question was about but since it does not do it, maybe this is for a different click event?

**Comment by jasondavis** [comment]
An update, I have found how out more information.  

Here is an image that is more to the point of the problem... You have to click in the area highlighted with red for it to work as expected.  So if you click anywhere outside of that red box it will not work, including on the actual text/name of the tag

![click area](http://codedevelopr.com/uploads/tag.png)

The ideal solution would allow you to click anywhere in the GREEN highlighted section to add that tag to the input box.  
![click area](http://codedevelopr.com/uploads/taggreen.png)

If you watch this 2 minute video you can see, I am on Windows 7 with Chrome http://screencastle.com/watch/00ca12cc4d3e10de867b8404007f85a4

**Comment by martinffx** [comment]
Any chance of merging one of these fixes into the main project

**Comment by alexgorbatchev** [comment]
Will merge it this weekend. Sorry about delay on this.

**Comment by alexgorbatchev** [comment]
Thank you!

**Comment by alexgorbatchev** [comment]
Merged.
