### ISSUE TITLE
prompt text is not aware of the right edge of the input box

### ISSUE THREAD

**Issue by codylindley** [alexgorbatchev/jquery-textext#22]
If the words push the prompt to the right, but the words do not go to a second line neither does the prompt. Depending up the width this make the prompt look broken as it goes out of the input to the right.

Here is a screenshot from the demo's.

http://gyazo.com/fb7bc9888402c86e8fb5fede63bde639

**Comment by alexgorbatchev** [comment]
Hm... how do you think it should be solved?

**Comment by burinov** [comment]
I think it should extend height of the input field, so, tags will continue as a second line.

@added: It already does it. PERFECT!
