### ISSUE TITLE
here's the code for a tiny "clear contents" plugin. Feedback?

### ISSUE THREAD

**Issue by mreinstein** [alexgorbatchev/jquery-textext#24]
I wrote a very simple plugin for adding a clear button (an "x" to the left of the arrow plugin) It's basically the same as the clear button in google docs; clicking it removes all tags and text from the textarea

js:     http://pastebin.com/C7kJig1R
css:  http://pastebin.com/dBQXBv8T

Anyone find this useful? I'd love feedback on the code; i basically just copied the arrow plugin and changed the p.onArrowClick function. I'm not sure if I'm following textext conventions in that code.

**Comment by sstok** [comment]
Considering your removing all tags its wise to have a way of asking for confirmation (like a pre-callback).
Or a way to undo changes (pre-callback & post-callback).

**Comment by mreinstein** [comment]
Can you elaborate a little more? Are you suggesting having the plugin fire an event before it's actually cleared to provide a hook for confirm dialogs, etc?

**Comment by sstok** [comment]
Yes :) typing one value is not bad. But typing all (after accidental remove) of is not.

**Comment by mreinstein** [comment]
dang, that is the fastest reply ever! :P 

Ok, I think that's a good idea. I'm not _entirely_ sure how to create a cancelable event in textext but I'll take a look at the other plugins and see if I can mangle something together. :)

**Comment by mreinstein** [comment]
btw is there a preferred way to share the progress? pastebin rocks but I feel dirty using it here. Maybe a gist instead?

**Comment by sstok** [comment]
I think making an personal repository is best, also because your having an CSS file.

Making a confirmation check can be tricky, just calling an function and checking whether it returned false does not work in a JavaScript world since for example a jQuery UI dialog uses callbacks that get fired later.

Maybe you can get some inspiration from the newly added tagClick event handler.

**Comment by balupton** [comment]
Pastebin links are dead. And I'm having a hell of a time trying to figure out how to clear my textext instance :(

**Comment by mreinstein** [comment]
New links for the plugin
js:     http://pastebin.com/W7zSkiXx
css:  http://pastebin.com/Y7ehDBAi

I never got around to sending Alex a pull request. Let me know if you have any problems using this.

**Comment by mreinstein** [comment]
I submitted a pull request for this to Alex.

https://github.com/mreinstein/jquery-textext/commit/6101c2c64cb2c5d2139ee3939080b3e15354ffb2

**Comment by geetanjaligg** [comment]
New links? Really hard time to figure out how to clear the tags!! :X

**Comment by mreinstein** [comment]
Alex  has merged this into his code. You should be able to use it if you pull Alex's latest.
