### ISSUE TITLE
Can not make the tag Unique

### ISSUE THREAD

**Issue by filod** [alexgorbatchev/jquery-textext#27]
if i want to create a friend selector,
my data point is like:
[
 { id : 1, name : 'bob"  ,avatar: "1.jpg" } ,
 { id : 2, name : 'bob"  ,avatar: "2.jpg" } ,
 { id : 3, name : 'bob"  ,avatar: "3.jpg" } ,
 ]

as U see, 3 friends have the same name, but diffrent avatar, with custom "autocomplete.render" method I can distinguish them.

but in custom stringToItem , i don't know  how to distinguish them ~~

**Comment by alexgorbatchev** [comment]
@filod This is more of application design issue rather than TextExt. Are there functionality issues that you are experiencing caused by displaying the same name?

**Comment by filod** [comment]
TextExt is very good, i like it .

As i have said above,  tag ( & other plugins ) use [ stringToItem ] to set formvalue , when user press enter key，via user input I can‘t know  the [ id ]  of user( in a website, we allow same username, but different [ id ].
maybe my problem is， how can I get the element i chose in autocomplete dropdown ? so that i can use it in the [ stringToItem ] to get the right item.

i find a way to do this in  [ stringToItem ], it's like :

```
               stringToItem : function(str){                
                    var item;
                    item =  $('#txtid').textext()[0].autocomplete().selectedSuggestionElement().data('text-suggestion');
                    if(item){
                        return item;
                    }
                            // other filter to get item;
                    return item;
               }
```

the way i used will be allright in the future TextExt ?

**Comment by alexgorbatchev** [comment]
There's currently no way to know in stringToItem() which particular HTML element was clicked... You would have to hack up autocomplete to pass that down the chain.
