### ISSUE TITLE
Downloaded sources not working

### ISSUE THREAD

**Issue by gruby-karol** [alexgorbatchev/jquery-textext#33]
I downloaded textext source files (.zip) from github , unzipped them and tried to use in my project.
It doesn't work. The files are loaded properly, no JS errors in the console (chrome).
The input field is empty. The tags are printed below to the left. "Add one" is shown bottom-right.
When I use combined source (from http://bundlejs.com/alexgorbatchev/products/textext/1.3.0) everything works fine.

It turns out that the combined file includes code that sets the styles.
The code begins with:

```
(function(a) {
    var b = document, c = "getElementsByTagName", d = b[c]("head")[0]
            || b[c]("body")[0], e = b.createElement("style");
    e.innerHTML = a, d.appendChild(e)
})
```

Maybe github distribution (or the manual) should be updated?

Hope this helps someone ;-)

**Comment by alexgorbatchev** [comment]
If you are using uncompressed files, you need to include appropriate CSS files for each plug in.

**Comment by gruby-karol** [comment]
Now I know :)
