### ISSUE TITLE
Click on scrollbar in dropdown makes list disappear

### ISSUE THREAD

**Issue by fabricasapiens** [alexgorbatchev/jquery-textext#4]
In Chrome on Windows, a click on the scrollbar (as for example on the homepage http://textextjs.com/) will make the list disappear instead of scroll.

**Comment by alexgorbatchev** [comment]
Thank you for reporting this.

**Comment by alexgorbatchev** [comment]
@fabricasapiens Sounds like there is a small number of issues specific to Windows. Unfortunately I don't have a readily available windows environment, do you think it's something you could look into?

**Comment by fabricasapiens** [comment]
I would assume it's the same issue with Chrome/Chromium across OS but I will try to look into this when I have the time! I think it has to do with not calling an event.preventDefault(); and event.stopPropagation(); somewhere...

**Comment by fabricasapiens** [comment]
Sweet :)

**Comment by alexgorbatchev** [comment]
@adamayres great, thank you! I'll have a look at this shortly.

**Comment by alexgorbatchev** [comment]
Merged.
