### ISSUE TITLE
Add ids for values

### ISSUE THREAD

**Issue by nikepan** [alexgorbatchev/jquery-textext#47]
For example

1, Delphi
2, C#

And keep it fpr processing. It is need for Arrow plugin

Thank you for good component!

**Comment by nikepan** [comment]
I wrote ItemManager for this. Not very good, but working.

**Comment by alexgorbatchev** [comment]
@nikepan That's exactly what `ItemManager` is for. Perhaps it might be a good idea to include a bunch of "common" types of managers? Could you pastebin yours?

**Comment by iambibhas** [comment]
@alexgorbatchev Even with `ItemManager`, the `stringToItem` method can only have access to the string value of the suggestion. So the server received the label only. Anyway we can send the `id` too?

I just saw an open issue for this: #73 , Any update?
