### ISSUE TITLE
Full dropdown when arrow clicked

### ISSUE THREAD

**Issue by nikepan** [alexgorbatchev/jquery-textext#49]
If I clicked new combobox on arrow at with text, then I see full dropdown. But when I typed something, then select Item. Next click on arrow shows only 1 item. Filter remember last query and for next select I need clear field. It not useful.

For example, vk.com working that. Thank you.

**Comment by alexgorbatchev** [comment]
@nikepan If you look at the example page http://textextjs.com/manual/examples/arrow-with-autocomplete.html you can see that filtering happens in the `getSuggestions` event handler, specifically in `{ result : textext.itemManager().filter(list, query) }`. You can control which items are returned by modifying this.
