### ISSUE TITLE
tagClick event not coming through to handler

### ISSUE THREAD

**Issue by leopoldodonnell** [alexgorbatchev/jquery-textext#51]
At present the 'Tag Click Event Changing Tag Value' demo does not work on Chrome or Safari on Max OS X Lion (not sure about other platforms).

The code approach to binding the event works fine in my own code, but the demo appears broken.

**Comment by alexgorbatchev** [comment]
@leopoldodonnell You are talking about http://textextjs.com/manual/examples/tags-click.html this page, right? It works for me in Chrome 18 and Safari 5. Could you please post details to reproduce?
