### ISSUE TITLE
search query not cleared after selecting item

### ISSUE THREAD

**Issue by rphutchinson** [alexgorbatchev/jquery-textext#55]
After selecting an item the search query for autocomplete should be cleared.  you can see this on example on the homepage.  type "C" into the input field and pick one of the two options and hit enter to select that item.  Now without typing anything else click the arrow for the dropdown.  Since there is no new text entered you should expect to see all the possible options but the only only options available are the same two from when I had entered "C" before.

**Comment by SharpNoiZy** [comment]
Yes, this is realy an ugly bug, please fix this one!!!

**Comment by alexgorbatchev** [comment]
Works as expected in 2.0. Won't be fixing in 1.3 unless somebody is kind enough to submit a patch.
