### ISSUE TITLE
not work in IE?

### ISSUE THREAD

**Issue by rqx110** [alexgorbatchev/jquery-textext#59]
The plugin doesn't work in IE.(I test on IE 8)

**Comment by sstok** [comment]
Validate the HTML http://validator.w3.org/ and make sure you're JavaScript is valid as well.
IE loves to trip over trailing comma's in an array/object definition.

**Comment by SharpNoiZy** [comment]
I don't think that this issue can be closed, I have the same problem with IE 8.
Also http://textextjs.com doesn't work, call your own site with IE8 and you will see a borken site.

**Comment by rqx110** [comment]
try to use the latest jQuery.

**Comment by ghost** [comment]
Was already been solved here: https://github.com/alexgorbatchev/jquery-textext/issues/38

edit: does not help me... ie 8 stil does not work:(

**Comment by boo2harold** [comment]
Hi, IE issue is fixed . 
Remove the auto.js  line from 4777 to end  and add this css to  that file which contain suggest field . 
Please remove new line and \ sign from css file .

**Comment by shaifymehtadnn** [comment]
again not problem solved for me.... can u send me the source or actual working one...

**Comment by shaifymehtadnn** [comment]
not working in IE 8

**Comment by wrygiel** [comment]
Confirmed! The issue was that innerHTML was called directly: http://i.imgur.com/erCNMvD.png. Once I moved the CSS to a separate file, it started working on IE8!
