### ISSUE TITLE
Feature request: separated .css file

### ISSUE THREAD

**Issue by rootical** [alexgorbatchev/jquery-textext#62]
I think it would be a nice feature. Why is it generating by the script?

I am having problems with styleing the plugins. Is there any little guide for that? I have good knowledge in css, but the height of container is generated in style attribute and i don`t know how to increase it.. and so on.

Thanks for the great plugin.

**Comment by alexgorbatchev** [comment]
You can't increase the height because it's automatically calculated if you are using tags plugin. There CSS files are available in the source here so you should be able to edit them directly if you need to.
