### ISSUE TITLE
Facing issue in submitting the form data.

### ISSUE THREAD

**Issue by Arthanari** [alexgorbatchev/jquery-textext#67]
As a part of learnign jQuery i have been trying to use your component Textext plugin. I am able to only see the items added in the text area in the hidden form input using firebug. but post that not sure how  to get it to the backend. Also as there is no id for the hidden input i am not sure how to get the values selected to the backend. Can you please help me with this.In my experimental application i might need more than 1 such intelligent text input, what all chnages i should do or include in such cases.

If i can get to see a sample where with the press of the submit button the values added in the textbox are added to an array which can be sent ot the backend, it would be of great help for me. Any support will be of great help for me.

I also tried some other similar components but am very much impressed by the professional look and feel of your design. So have made up my mind to use TextExt Plugin. Kindly find some time to support me in this.

**Comment by r3verser** [comment]
``` javascript
$('#textarea').textext({
          html: {
               hidden: ('<input type="hidden" name="tags" />')
          },
          plugins : 'autocomplete tags ajax',
          ajax : {
               url : '/suggest',
               dataType : 'json',
               cacheResults : false
          }
     });
```

Just setup html.hidden option. After that, in $_POST['tags'] should be your tags in json format. Don't forget to json_decode them.

**Comment by shaifymehtadnn** [comment]
hmm thanxxxx :thumbsup:
