### ISSUE TITLE
Is it possible to load textext at the bottom of the page instead of directly after the textarea?

### ISSUE THREAD

**Issue by joshgarwood** [alexgorbatchev/jquery-textext#69]
Hi there!

First, I love what I've seen of this plugin thus far; it's clear and easy to use, and has all of the features I'm looking for :)  The one problem I'm having is being able to load textext anywhere other than an inline script tag directly after the targeted text area element.  So for instance, I have a javascript file that loads all of my other components positioned at the bottom of the page just before the closing <body> tag.  My hope was that I could call:

$('#textarea').textext({
                plugins: 'autocomplete suggestions filter tags',
                suggestions: [
                    'Health',
                    'Social',
                    'Professional'
                ]
            });

Inside of that javascript file, but unfortunately this does not seem to work at all.  In order for it to work I have to place the above in a script tag, and place the script tag directly after the <textarea> within the HTML.  I may be missing something, but this is less than ideal for me :)  Is there a way around this?

Thanks again for all the great work!!

**Comment by vbogoev** [comment]
Put your code in "document ready" block. I think that's your problem. 

Best Regards! :)

**Comment by joshgarwood** [comment]
Thanks so much for the reply; much appreciated!

Unfortunately though, this did not solve my problem :(  While the plug-in does in fact seem to initialize (the HTML markup for it is created), the autocomplete piece is not working.  When I type a word that is in the suggestions array above, nothing seems to happen.  There are no javascript errors, and no real indication of a problem, other than the autocomplete box doesn't appear.  If I place the javascript above directly after the targeted textarea in the HTML though, it works as expected.  However, if I instead call it from within a separate .js file that is located just before the close of the body tag, the autocomplete does not work :(  Is there anything in particular that I need to do to ensure that the autocomplete plugin is loaded?

Thanks again!!

**Comment by alexgorbatchev** [comment]
As was mentioned, the call/load order is significant. TextExt expects the input box to be ready to use when it is called, be that on `document.ready` or directly after the tag declaration.
