### ISSUE TITLE
Not working with jQuery >=1.8.0

### ISSUE THREAD

**Issue by ikostia** [alexgorbatchev/jquery-textext#74]
Probably this is somehow related to other styling (width) issues but I'm not sure.

If one takes the main page `http://textextjs.com/` and substitutes `jQuery-1.6.1.js` which is used to `jQuery-1.8.0.js`, strange styling issues appear. Underlying textbox becomes visible to the right of styled textext input box. 

Here is a snapshot: `https://skitch.com/ikostia/euy82/jquery-textext-plugin`

Thanks,
Kostia

**Comment by halfdan** [comment]
I can confirm this issue. The Textbox just increases its width to the right for each new item added.

**Comment by vbogoev** [comment]
I'm using jQuery 1.8.0 and don't have any problems with width. However, I have another issue: All tags disappear when I move the mouse above the texext textarea... The most interesting thing is that it doesn't happen every time. Any ideas?

**Comment by yoanntrouillet** [comment]
We are using your plugin (excellent work btw) but since we upgraded to jQuery 1.8.2 (and twitter boostrap 2.1.1) the plugin has issues - we cannot view/create/deletes tags. No js error is thrown however.

**Comment by mimo84** [comment]
I can confirm this issue, in jQueryt 1.8+. Also if you have to write something wider than the size of the input, the text disappear until you don't press enter.

**Comment by alexgorbatchev** [comment]
Thanks for reporting this. I haven't had a chance to try jQuery 1.8 yet. Has anyone tried diagnosing the issue yet?

**Comment by FaFiNoS** [comment]
I've commented line 981 (not compressed js of course) and issue with textbox width disappeared. Textbox width need to be set by class or inline style. I'm using jQuery 1.8.2 and jQuery-UI 1.8.24.

..
981:    //input.width(width)
..

**Comment by andrusha** [comment]
@yoanntrouillet I have similar issue with jQuery 1.7.2 and Bootstrap 2.0.4

**Comment by andrusha** [comment]
Doesn't work with 1.8.2 and no-conflict 1.6.1 either.

**Comment by alexgorbatchev** [comment]
Thanks for everyone reporting this and especially to @FaFiNoS for finding the root cause. Here's the commit that fixes this

https://github.com/alexgorbatchev/jquery-textext/commit/d02ff705bf8c50ce798e16e6177607ae57ba4299
