### ISSUE TITLE
focus and unfocus problem

### ISSUE THREAD

**Issue by irfanevrens** [alexgorbatchev/jquery-textext#81]
I click a textext activated textarea element and so my element is focused. Then I click outside of my element, so unfocused. But at that time, Firebug console fire an error

"uncaught exception: Syntax error, unrecognized expression: Syntax error, unrecognized expression: focus"

there is no problem on work but what is this error on backend.

activated plugins: autocomplete tags ajax prompt focus

**Comment by alexgorbatchev** [comment]
What firefox version are you using? Can you reproduce this on http://textextjs.com ?
