### ISSUE TITLE
Intenet Explorer 8 compatibility Issue

### ISSUE THREAD

**Issue by shaifymehtadnn** [alexgorbatchev/jquery-textext#88]
This plugin is not working in internet explorer 8 . i have checked on the multiple computers... but plugin is working smoothly on internet explorer 9

**Comment by apolzon** [comment]
I second this.  Breaks all javascript execution on the page.

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C)
Timestamp: Tue, 6 Nov 2012 00:15:24 UTC

Message: Unknown runtime error
Line: 3833
Char: 117
Code: 0
URI: http://localhost:3000/assets/textext.bundle.js?body=1

**Comment by shaifymehtadnn** [comment]
replace

e.innerHTML=a,d.appendChild(e)

with

$(d).append("<style>"+ a+ "</style>")

in the "TextExt.js" file....

this will resolved the problem..
