### ISSUE TITLE
isTagAllowed called twice

### ISSUE THREAD

**Issue by MadeByMike** [alexgorbatchev/jquery-textext#89]
isTagAllowed is triggered first by onEnterKeyPress then again by addTags for the same tag.

This makes it difficult to keep track of used tags. It really only should be called once per tag and addTags seems the more logical place.

I suggest removing the lines commented out below

``` javascript
p.onEnterKeyPress = function(e){
        var self = this,
            val  = self.val(),
            tag  = self.itemManager().stringToItem(val)
            ;

    //  if(self.isTagAllowed(tag)){
            self.addTags([ tag ]);
            // refocus the textarea just in case it lost the focus
            self.core().focusInput();
    //  }
};
```

**Comment by ruudk** [comment]
I noticed this too. Why don't u send a PR that removes the code?

**Comment by alexgorbatchev** [comment]
Related to #85
