### ISSUE TITLE
Make the autocompletition search not just in the beginning of the strings

### ISSUE THREAD

**Issue by petkos** [alexgorbatchev/jquery-textext#93]
This is my list:

```
["apple", "pie", "bar"] 
```

and I want when the user enters a letter, all the words which CONTAIN that letter to list, not just the words that BEGIN with that letter.  How to do this?

I use this js file: http://muraliprashanth.me/wp-content/uploads/2012/11/autocomplete.js

**Comment by alexgorbatchev** [comment]
You can create your own [ItemManager](http://textextjs.com/manual/itemmanager.html) and override `itemContains(item, needle)`
